ctx_templates = [
        "a photo of a {}.",
        "a photo of a {}, upside-down.",
        "a photo of a {}, the photo is upside-down.",
        "a photo of a {}, the photo is upright.",
        "a photo of a {}, rotated.",
        "a photo of a {}, the photo is rotated.",
        "a photo of a {}, upright.",
        "a photo of a {}, distorted.",
        "a photo of a {}, the photo is distorted.",
        "a photo of a {}, color-inverted.",
        "a photo of a {}, the photo is color-inverted.",
        "a photo of a {}, solarized.",
        "a photo of a {}, the photo is solarized.",
        "a photo of a {}, normal.",
        "a photo of a {}, the photo is normal.",
        "a photo of a {}, blurred.",
        "a photo of a {}, the photo is blurred.",
        "a photo of a {}, grayscale.",
        "a photo of a {}, the photo is in black and white.",
        "a photo of a {}, colorful.",
        "a photo of a {}, the photo is colorful.",
        "a photo of a {}, bright.",
        "a photo of a {}, the photo is bright.",
        "a photo of a {}, dark.",
        "a photo of a {}, the photo is dark.",
        "a photo of a {}, with noise.",
        "a photo of a {}, the photo has noise.",
        "a photo of a {}, in the snow.",
        "a photo of a {}, the photo is in the snow.",
        "a photo of a {}, in the frost.",
        "a photo of a {}, the photo is in the frost.",
        "a photo of a {}, in the fog.",
        "a photo of a {}, the photo is in the fog.",
        "a photo of a {}, clear.",
        "a photo of a {}, the photo is clear.",
        "a photo of a {}, in jpeg format.",
        "a photo of a {}, the photo is in jpeg format.",
        "a photo of a {}, in high resolution.",
        "a photo of a {}, the photo is in high resolution.",
        "a photo of a {}, upside-down, color-inverted.",
        "a photo of a {}, the photo is upside-down, color-inverted.",
        "a photo of a {}, upright, normal.",
        "a photo of a {}, the photo is upright, normal.",
        "a photo of a {}, grayscale, with distortion.",
        "a photo of a {}, the photo is distorted, in black and white.",
        "a photo of a {}, colorful, normal.",
        "a photo of a {}, the photo is colorful, normal."
    ]

